id: P8C759FF6
initial_creation_type: input
source_metadata:
  Title: Smāhitā Bhūmiḥ
  Editor: '-'
  Publisher: Arbeitskreis Fur Tibetische Und Buddhistische Studien, Universitat Wien
  Place of Publication: Wien
  Year: '2009'
  Smāhitā Bhūmiḥ:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: June, 2017
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:05:51.071896'
last_modified_at: '2022-03-08T17:05:51.071903'
